server:
  port: 8761
  
spring:
  application:
    name: eureka-crud-server
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultzone: ${EUREKA_SERVER:http://localhost:8761/eureka/}