version: '3'
services:
  eureka-crud-server:
    image: eureka-crud-server:1.0
    container_name: eureka-crud-server
    expose:
    - "8761"
    ports:
    - 8761:8761
  employee-crud-microservice:
    image: employee-crud-microservice:1.0
    #container_name: employee-crud-microservice
    ports:
    - 8680:8680
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-crud-server:8761/eureka  -DDB_USER=root -DDB_PASSWORD=1234 -DJDBC=jdbc:mariadb://localhost:3306/employeeservice

    links:
        - eureka-crud-server

  